// libs/react/ui/src/lib/Button/BuyDeHubButton.tsx
import { MenuItem } from 'primereact/menuitem';
import { SplitButton } from 'primereact/splitbutton';
import { useMemo } from 'react';

const BuyDeHubButton = ({
  cexUrl,
  downloadWalletUrl,
  onBuy,
  onDexSelected,
}: {
  cexUrl: string;
  downloadWalletUrl: string;
  onBuy: () => void;
  onDexSelected: () => void;
}) => {
  const items: MenuItem[] = useMemo(
    () => [
      {
        label: 'DEX',
        command: onDexSelected,
      },
      {
        label: 'CEX',
        command: () => window.open(cexUrl, '_blank'),
      },
      {
        label: 'Download Wallet',
        command: () => window.open(downloadWalletUrl, '_blank'),
      },
    ],
    [cexUrl, downloadWalletUrl, onDexSelected]
  );

  return (
    <SplitButton
      className="p-button-primary"
      label="Buy DeHub"
      model={items}
    ></SplitButton>
  );
};

export default BuyDeHubButton;

// libs/angular/ui/src/lib/components/buy-dehub-button/buy-dehub-button.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
} from '@angular/core';
import { MenuItem } from 'primeng/api';

@Component({
  selector: 'dhb-buy-dehub-button',
  template: `<p-splitButton
    [label]="label"
    [model]="items"
    (onClick)="buy.emit()"
  ></p-splitButton>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BuyDehubButtonComponent implements OnInit {
  @Input() label = 'Buy DeHub';
  @Input() cexUrl?: string;
  @Input() downloadWalletUrl?: string;

  @Output() buy = new EventEmitter<void>();
  @Output() dexSelected = new EventEmitter<void>();

  items: MenuItem[] = [];

  constructor() {}

  ngOnInit() {
    this.items = [
      {
        label: 'DEX',
        command: () => this.dexSelected.emit(),
      },
      {
        label: 'CEX',
        url: this.cexUrl,
        target: '_blank',
      },
      {
        label: 'Download Wallet',
        url: this.downloadWalletUrl,
        target: '_blank',
      },
    ];
  }
}
