// libs/react/ui/src/lib/Button/BuyDeHubButton.tsx
import { MenuItem } from 'primereact/menuitem';
import { SplitButton } from 'primereact/splitbutton';
import { useMemo } from 'react';

const BuyDeHubButton = ({
  cexUrl,
  downloadWalletUrl,
  onBuyWithCard,
}: {
  cexUrl: string;
  downloadWalletUrl: string;
  onBuyWithCard: () => void;
}) => {
  const items: MenuItem[] = useMemo(
    () => [
      {
        label: 'Buy With Card',
        command: onBuyWithCard,
      },
      {
        label: 'CEX',
        command: () => window.open(cexUrl, '_blank'),
      },
      {
        label: 'Download Wallet',
        command: () => window.open(downloadWalletUrl, '_blank'),
      },
    ],
    [cexUrl, downloadWalletUrl, onBuyWithCard]
  );

  return (
    <SplitButton
      className="p-button-primary"
      label="Buy DeHub"
      model={items}
    ></SplitButton>
  );
};

export default BuyDeHubButton;

// libs/angular/ui/src/lib/components/buttons/buy-dehub-button/buy-dehub-button.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
} from '@angular/core';
import { Router } from '@angular/router';
import { MenuItem } from 'primeng/api';

@Component({
  selector: 'dhb-buy-dehub-button',
  template: ` <!-- https://github.com/DeHubToken/dehub-nx/issues/353 -->
    <!-- <p-splitButton
    [label]="label"
    [model]="items"
    (onClick)="onBuyClicked($event)"
  ></p-splitButton> -->
    <p-button [label]="label" (onClick)="onBuyClicked()"></p-button>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class BuyDehubButtonComponent implements OnInit {
  @Input() label = 'Buy DeHub';
  @Input() cexUrl?: string;
  @Input() downloadWalletUrl?: string;

  @Output() buyWithCard = new EventEmitter<void>();

  items: MenuItem[] = [];

  constructor(private router: Router) {}

  ngOnInit() {
    this.items = [
      {
        label: 'Buy With Card',
        command: () => this.buyWithCard.emit(),
      },
      {
        label: 'CEX',
        url: this.cexUrl,
        target: '_blank',
      },
      {
        label: 'Download Wallet',
        url: this.downloadWalletUrl,
        target: '_blank',
      },
    ];
  }

  onBuyClicked() {
    this.router.navigate(['/shop']);
  }
}
